language: ruby
rvm:
  - 2.5
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
install:
  - gem install cfhighlander cfn-nag rspec
  - pip3 install --user cfn-lint
before_script:
  - cfndsl -u
script:
  - rspec
  - cfn_nag_scan -i out/tests
  - cfn-lint out/tests/**/*.yaml -i W1020
